module.exports = {
  NEW_CHAT_EVENT: 'NEW_CHAT_EVENT',
  NEW_MESSAGE_EVENT: 'NEW_MESSAGE_EVENT',
  NEW_MEMBER_EVENT: 'NEW_MEMBER_EVENT',
  CREATE_CHAT_EVENT: 'CREATE_CHAT_EVENT',
  START_TYPING_EVENT: 'START_TYPING_EVENT',
};
