export const NEW_CHAT_EVENT = 'NEW_CHAT_EVENT';
export const NEW_MESSAGE_EVENT = 'NEW_MESSAGE_EVENT';
export const NEW_MEMBER_EVENT = 'NEW_MEMBER_EVENT';
export const CREATE_CHAT_EVENT = 'CREATE_CHAT_EVENT';

export const START_TYPING_EVENT = 'START_TYPING_EVENT';
