/*
 * auth action types
 * */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const REFRESH_AUTH = 'REFRESH_AUTH';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
/*
 * chat action types
 * */
export const LOAD_CHATS_REQUEST = 'LOAD_CHATS_REQUEST';
export const LOAD_CHATS_SUCCESS = 'LOAD_CHATS_SUCCESS';
export const LOAD_CHATS_ERROR = 'LOAD_CHATS_ERROR';

export const SELECT_CHAT_ACTION = 'SELECT_CHAT_ACTION';

export const SELECTED_CHAT_LOAD_DATA_SUCCESS = 'SELECTED_CHAT_LOAD_DATA_SUCCESS';

export const CREATE_CHAT_ACTION = 'CREATE_CHAT_ACTION';
export const NEW_CHAT_ACTION = 'NEW_CHAT_ACTION';
export const NEW_CHAT_MESSAGE_ACTION = 'NEW_CHAT_MESSAGE_ACTION';
export const NEW_CHAT_MEMBER_ACTION = 'NEW_CHAT_MEMBER_ACTION';
export const LOAD_USERS_ACTION = 'LOAD_USERS_ACTION';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const SEND_MESSAGE_ACTION = 'SEND_MESSAGE_ACTION';